# See https://github.com/bxparks/EpoxyDuino for documentation about this
# Makefile to compile and run Arduino programs natively on Linux or MacOS.

APP_NAME := SimultaneousButtons
ARDUINO_LIBS := AceButton 
include ../../../EpoxyDuino/EpoxyDuino.mk
