// The AUNITER_ARDUINO_BINARY environment variable is defined in the Jenkins
// system configuration.
//
// The WORKSPACE variable is automatically filled in by Jenkins.
//
// The BOARDS variable is defined in the "This project is
// parameterized" section of the Pipeline configuration.
//
pipeline {
    agent { label 'master' }
    stages {
        stage('Setup') {
            steps {
                dir('AUniter') {
                    git url: 'https://github.com/bxparks/AUniter',
                        branch: 'develop'
                }
                dir('libraries/AUnit') {
                    git url: 'https://github.com/bxparks/AUnit',
                        branch: 'develop'
                }
            }
        }
        stage('Verify Examples') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceButton/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceButton/examples/*"
            }
        }
        stage('Verify Tests') {
            steps {
                sh "AUniter/auniter.sh --verify \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceButton/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceButton/tests/AceButtonTest"
            }
        }
        stage('Test') {
            steps {
                sh "AUniter/auniter.sh --test \
                    --pref sketchbook.path=$WORKSPACE \
                    --config libraries/AceButton/tests/auniter.conf \
                    --boards $BOARDS \
                    libraries/AceButton/tests/AceButtonTest"
            }
        }
    }
}
