# See https://github.com/bxparks/AUnit/tree/develop/unitduino for documentation
# about using unitduino to compile and run AUnit tests natively on Linux or
# MacOS.

APP_NAME := AceButtonTest
ARDUINO_LIBS := AceButton
include ../../../AUnit/unitduino/unitduino.mk
